name: Test

on:
  - pull_request
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: setup yarn
        run: npm install -g yarn

      - name: setup yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn

      - name: install deps
        run: |
          yarn install --immutable --immutable-cache --check-cache

      - name: run tests
        run: |
          yarn run test
